name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Copy repository contents via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: "/var/www/port-folio"

    - name: Execute remote build and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          set -e
          cd /var/www/port-folio

          # Optional: install pnpm if not already installed
          if ! command -v pnpm &> /dev/null; then
            curl -fsSL https://get.pnpm.io/install.sh | sh -
          fi

          # This line modifies the PATH environment variable so the shell can find and run pnpm commands that were installed in a user-specific location.
          export PATH="$HOME/.local/share/pnpm:$PATH"

          rm -rf .next node_modules

          pnpm install
          pnpm build

          pm2 restart port-folio || pm2 start pnpm --name "port-folio" -- start
