name: Deploy

# on: [push] # Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main  # Only trigger when there's a push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Copy repository contents via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: "/var/www/port-folio"

    - name: Execute remote build and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/port-folio
          export PATH="$HOME/.local/share/pnpm:$PATH"
          pnpm install --frozen-lockfile
          pnpm build
          pm2 restart port-folio || pm2 start pnpm --name "port-folio" -- start
